export type Repository = {
  id: string;
  installation_id: string;
  full_name: string;
  enabled: boolean;
  connected: boolean;
  labels_enabled: boolean;
};
export type Run = {
  id: string;
  repository_id: string;
  pr_number: number;
  title: string;
  head_sha: string;
  base_sha: string;
  status: "queued" | "running" | "completed" | "failed" | "cancelled";
  stage: string;
  attempts: number;
  created_at: Date | string;
  started_at: Date | string | null;
  completed_at: Date | string | null;
  result: ReviewResult | null;
  error: string | null;
  check_id: string | null;
  summary_id: string | null;
  review_id: string | null;
  publication_started: boolean;
  tokens: number | string;
  model: string | null;
  full_name?: string;
};
export type Finding = {
  source: "ai" | "security-audit" | "semgrep" | "gitleaks";
  severity: "critical" | "high" | "medium" | "low";
  path: string;
  line: number;
  title: string;
  description: string;
  evidence: string;
  recommendation: string;
};
export type SourceFile = { path: string; content: string; patch: string };
export type SecurityAuditResult = {
  status: "completed" | "disabled";
  scope: "changed-files";
  summary: string;
  skills: { id: string; name: string; sha256: string }[];
  tokens: number;
  model: string | null;
  candidates: number;
  retained: number;
  verification: "source-model-pass" | "no-candidates" | "not-run";
  discoveryBatches?: number;
  verificationBatches?: number;
};
export type ReviewResult = {
  summary: string;
  findings: Finding[];
  files: number;
  skipped: string[];
  coverage: "complete" | "partial";
  scanners: string[];
  warnings: string[];
  securityAudit?: SecurityAuditResult;
  reviewSkills?: { id: string; name: string; sha256: string }[];
  reviewBatches?: number;
};
